apiVersion: "jjsair0412.example.com/v1"
kind: helloworld
metadata:
  name: hello-sample
# required option
spec:
  # required option
  appId: "hello-worldd-jin"
  replicas: 1
  message: "hi"
  image: nginx
  language: python
