apiVersion: v1
kind: Service
metadata:
  name: {{ include "cicd-gradle.fullname" . }}
  labels:
    {{- include "cicd-gradle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7100
      protocol: TCP
      name: http
  selector:
    {{- include "cicd-gradle.selectorLabels" . | nindent 4 }}
