logging:
  level:
    '[org.springframework.web]': debug

server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
      - id: first_route
        uri: http://localhost:8001/
        predicates:
        - Path=/first_route/**
      - id: second_route
        uri: http://localhost:8002/
        predicates:
        - Path=/second_route/**
    