# Affinity 설정
nodeAffinity: {}

# user 설정
extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-jinseong-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-jinseong-credentials
        key: username

extraVolumes:
- name: elastic-certificates
  emptyDir: {}

extraVolumeMounts:
- name: jinseong-tls
  mountPath: /usr/share/elasticsearch/config/certs
- name: elastic-certificates
  mountPath: /usr/share/elasticsearch/config/certs-gen

secretMounts:
- name: jinseong-tls
  secretName: jinseong-tls-gen
  path: /usr/share/elasticsearch/config/certs


esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true
    xpack.security.transport.ssl.verification_mode: certificate
    xpack.security.transport.ssl.client_authentication: required
    xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs-gen/elastic-cert.p12
    xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs-gen/elastic-cert.p12

extraInitContainers:
- name: setup-tls-cert
  image: "docker.elastic.co/elasticsearch/elasticsearch:7.10.0"
  command:
  - sh
  - -c
  - |
    #!/usr/bin/env bash

    if [[ ! -f /usr/share/elasticsearch/config/certs-gen/elastic-cert.p12 ]]; then
      ./bin/elasticsearch-certutil cert \
        --name ${NODE_NAME} \
        --days 1000 \
        --ip ${POD_IP} \
        --dns ${NODE_NAME},${POD_SERVICE_NAME},${POD_SERVICE_NAME_HEADLESS},${NODE_NAME}.${POD_SERVICE_NAME},${NODE_NAME}.${POD_SERVICE_NAME_HEADLESS} \
        --ca-cert /usr/share/elasticsearch/config/certs/tls.crt \
        --ca-key /usr/share/elasticsearch/config/certs/tls.key  \
        --ca-pass "" \
        --pass "" \
        --out /usr/share/elasticsearch/config/certs-gen/elastic-cert.p12
    fi;

  env:
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: POD_SERVICE_NAME
    value: "elasticsearch-master"
  - name: POD_SERVICE_NAME_HEADLESS
    value: "elasticsearch-master-headless"
  volumeMounts:
  - name: jinseong-tls 
    mountPath: /usr/share/elasticsearch/config/certs
  - name: elastic-certificates
    mountPath: /usr/share/elasticsearch/config/certs-gen/es-certs