# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.boot_timeout = 1000
    config.vm.define "master" do |master| # | | 내부는 alias, 첫글자는 대문자가 올 수 없다.
  
      master.vm.box = "bento/ubuntu-20.04"
      master.vm.host_name = "master"
      master.vm.network "private_network", ip: "192.168.50.10"
      master.vm.provider :virtualbox do |masterSpec|
        masterSpec.memory =  16384
        masterSpec.cpus = 12
      end
    #   master.vm.provision "shell", path: "./script/common_config.sh"
    end
  
  end