# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.provider :virtualbox do |vb|
      vb.gui = true
    end
    config.vm.boot_timeout = 1000
    config.vm.define "redis" do |redis|
      redis.vm.network "forwarded_port", guest: 6379, host: 6379 # redis port
      redis.vm.box = "ubuntu/focal64"
      redis.vm.host_name = "redis"
      redis.vm.network "private_network", ip: "192.168.50.10"
      redis.vm.provider :virtualbox do |redisSpec|
        redisSpec.memory = 4096
        redisSpec.cpus = 4
      end
    end
  
    (1..2).each do |n|
      config.vm.define "tomcat-#{n}" do |tomcat|
        tomcat.vm.network "forwarded_port", guest: 8080, host: 8080 # tomcat port
        tomcat.vm.box = "ubuntu/focal64"
        tomcat.vm.host_name = "tomcat-#{n}"
        tomcat.vm.network "private_network", ip: "192.168.50.1#{n}"
        tomcat.vm.provider :virtualbox do |tomcatSpec|        
          tomcatSpec.memory = 4096
          tomcatSpec.cpus = 4
        end
      end
    end
  end