@startuml

title Main Logic Sequence Diagram

participant "메인 로직" as mainLogic

participant "ES 색인용 JSON 변환 로직" as jsonLogic

box "DataBase" #LightBlue
    database "ActionTable" as ActionTable
    database "Target Table" as TargetTable
end box

note over mainLogic
    대상 Event 목록
    - Insert
    - Update
    - Delete
    위 세가지 Event 중 한가지 발생 시 json 변환 로직으로 이동
end note

mainLogic->jsonLogic: Event 발생
activate mainLogic

activate jsonLogic
note right jsonLogic: ElasticSearch에 색인될 JSON 타입으로\n변경 정보를 변환합니다.\n그후, ActionTable에 생성된 JSON 값을 Insert 합니다.
jsonLogic->ActionTable

ActionTable-->jsonLogic: insert 결과 반환
deactivate

mainLogic->TargetTable: 변경 Event 정보 RDB에 반영

TargetTable-->mainLogic: Return Event Result




@enduml
