version: '3.7'
services:
  portal:
    container_name: portal
    image: nginx  
    ports:
      - 8080:80
    volumes: 
      - ./cluster/default.conf:/etc/nginx/conf.d/default.conf
  tomcat1:
    image: tomcat:7.0.94-jre7-alpine
    container_name: tomcat1
    volumes:
      - ./cluster/server.xml:/usr/local/tomcat/conf/server.xml
      - ./cluster/ROOT:/usr/local/tomcat/webapps/ROOT
      - ./cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
  tomcat2:
    image: tomcat:7.0.94-jre7-alpine
    container_name: tomcat2
    volumes:
      - ./cluster/server.xml:/usr/local/tomcat/conf/server.xml
      - ./cluster/ROOT:/usr/local/tomcat/webapps/ROOT
      - ./cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
  tomcat3:
    image: tomcat:7.0.94-jre7-alpine
    container_name: tomcat3
    volumes:
      - ./cluster/server.xml:/usr/local/tomcat/conf/server.xml
      - ./cluster/ROOT:/usr/local/tomcat/webapps/ROOT
      - ./cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml 

  redis_container:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf